package asaas

type ChargeStatus string

const (
	CHARGE_PENDING                      ChargeStatus = "PENDING"
	CHARGE_RECEIVED                     ChargeStatus = "RECEIVED"
	CHARGE_CONFIRMED                    ChargeStatus = "CONFIRMED"
	CHARGE_OVERDUE                      ChargeStatus = "OVERDUE"
	CHARGE_REFUNDED                     ChargeStatus = "REFUNDED"
	CHARGE_RECEIVED_IN_CASH             ChargeStatus = "RECEIVED_IN_CASH"
	CHARGE_REFUND_REQUESTED             ChargeStatus = "REFUND_REQUESTED"
	CHARGE_REFUND_IN_PROGRESS           ChargeStatus = "REFUND_IN_PROGRESS"
	CHARGE_CHARGEBACK_REQUESTED         ChargeStatus = "CHARGEBACK_REQUESTED"
	CHARGE_CHARGEBACK_DISPUTE           ChargeStatus = "CHARGEBACK_DISPUTE"
	CHARGE_AWAITING_CHARGEBACK_REVERSAL ChargeStatus = "AWAITING_CHARGEBACK_REVERSAL"
	CHARGE_DUNNING_REQUESTED            ChargeStatus = "DUNNING_REQUESTED"
	CHARGE_DUNNING_RECEIVED             ChargeStatus = "DUNNING_RECEIVED"
	CHARGE_AWAITING_RISK_ANALYSIS       ChargeStatus = "AWAITING_RISK_ANALYSIS"
)

func (c ChargeStatus) IsEnumValid() bool {
	switch c {
	case CHARGE_PENDING, CHARGE_RECEIVED, CHARGE_CONFIRMED, CHARGE_OVERDUE, CHARGE_REFUNDED, CHARGE_RECEIVED_IN_CASH,
		CHARGE_REFUND_REQUESTED, CHARGE_REFUND_IN_PROGRESS, CHARGE_CHARGEBACK_REQUESTED, CHARGE_CHARGEBACK_DISPUTE,
		CHARGE_AWAITING_CHARGEBACK_REVERSAL, CHARGE_DUNNING_REQUESTED, CHARGE_DUNNING_RECEIVED,
		CHARGE_AWAITING_RISK_ANALYSIS:
		return true
	}
	return false
}
