#file: noinspection SpellCheckingInspection
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
          go get github.com/mattn/goveralls
      - name: Build
        run: go build -v ./...
#      - name: Import Goveralls
#        run: go get github.com/mattn/goveralls
#      - name: Test Covarage
#        run: go test -v -covermode=count -coverprofile=coverage.out ./asaas/...
#      - name: Export Covarage
#        run: $GOPATH/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
